ConnectingToDB_Lab3/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.SqlServer;
using ConnectingToDB_Lab3.Data;
using ConnectingToDB_Lab3.Models;

namespace ConnectingToDB_Lab3.Controllers
{
    public class DepartmentController : Controller
    {
        ITIDBContext db = new ITIDBContext();
        //display all departments
        public IActionResult Index()
        {
            List<Department> departments = db.Departments.ToList();
            return View(departments);
        }

        //display adding form
        public IActionResult Create()
        {
            return View();
        }
        //savingData in database
        [HttpPost]
        public IActionResult Create(Department dept)
        {
            db.Departments.Add(dept);
            db.SaveChanges();
            return RedirectToAction("index");
        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Department dept = db.Departments.FirstOrDefault(a => a.DeptId == id);
            if (dept == null)
            {
                return NotFound();
            }
            return View(dept);
        }
        [HttpPost]
        public IActionResult Edit(Department dept)
        {
            db.Departments.Update(dept);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Department Dept = db.Departments.FirstOrDefault(a => a.DeptId == id);
            if(Dept == null)
            {
                return NotFound();
            }
            return View(Dept);
        }

        [ActionName("Delete")]

        [HttpPost] 
        public IActionResult DeleteConfirmed(int? deptid)          
        {
            //dept id because it's coming from form input with asp-for="deptid"
            //if we depended on id sent with route we would use param named id instead
            Department dept = db.Departments.FirstOrDefault(a => a.DeptId == deptid);
            db.Departments.Remove(dept);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ShowDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Department dept = db.Departments.FirstOrDefault(a => a.DeptId == id);
            if (dept == null)
            {
                return NotFound();
            }
            return View(dept);
        }

    }
}

ConnectingToDB_Lab3/Controllers/StudentController.cs
using ConnectingToDB_Lab3.Data;
using ConnectingToDB_Lab3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ConnectingToDB_Lab3.Controllers
{
    public class StudentController : Controller
    {
        ITIDBContext db = new ITIDBContext();
        public IActionResult Index()
        {
            List<Student> students = db.Students.Include(a => a.Department).ToList();
            return View(students);
        }
        public IActionResult Create()
        {
            ViewBag.depts = new SelectList(db.Departments.ToList(), "DeptId", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult Create(Student student, IFormFile stdimg)
        {
            if (stdimg == null)
            {
                ModelState.AddModelError("", "Img is required");
            }
            if (ModelState.IsValid == true)
            {
                db.Students.Add(student);
                db.SaveChanges();
                string[] arr = stdimg.FileName.Split('.');
                string filename = student.Id.ToString() + "." + arr[arr.Length - 1];
                using (var fs = new FileStream("./wwwroot/images/" + filename, FileMode.Create))
                {
                    stdimg.CopyTo(fs);
                }
                student.StdImg = filename;
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.depts = new SelectList(db.Departments.ToList(), "DeptId", "Name", student.DeptId);
            return View(student);

        }
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Student std = db.Students.Include(a => a.Department).FirstOrDefault(a => a.Id == id);
            if (std is null)
            {
                return NotFound();
            }
            return View(std);
        }
        public IActionResult checkusername(string UserName)
        {
            Student std = db.Students.FirstOrDefault(a => a.UserName == UserName);
            if (std == null)
                return Json(true);
            else
                return Json(false);
        }
        public IActionResult editFormOne(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Student std = db.Students.Include(a=>a.Department).FirstOrDefault(a => a.Id == id);
            if (std is null)
            {
                return NotFound();
            }
            ViewBag.depts = new SelectList(db.Departments.ToList(), "DeptId", "Name",std.DeptId);
            return View(std);
        }
        public IActionResult editFormTwo(Student std)
        {
            ViewBag.depts = new SelectList(db.Departments.ToList(), "DeptId", "Name", std.DeptId);
            return View(std);
        }
        public IActionResult editFormThree(Student std)
        {
            return View(std);
        }

        public IActionResult Edit(Student std,IFormFile stdimg)
        {
            if(stdimg == null)
            {
                ModelState.AddModelError("", "image is required");
            }

            if (ModelState.IsValid == true)
            {

                Student studentToBeUpdated = db.Students.FirstOrDefault(a => a.Id == std.Id);
                if (studentToBeUpdated == null)
                {
                    return NotFound();
                }
                else
                {
                    string[] arr = stdimg.FileName.Split('.');
                    string filename = std.Id.ToString() + "." + arr[arr.Length - 1];
                    using (var fs = new FileStream("./wwwroot/images/" + filename, FileMode.Create))
                    {
                        stdimg.CopyTo(fs);
                    }
                    std.StdImg = filename;
                    //Department selectedDept = db.Departments.FirstOrDefault(a => a.DeptId == std.DeptId);
                    
                    studentToBeUpdated.Name = std.Name;
                    studentToBeUpdated.Age = std.Age;
                    studentToBeUpdated.DeptId = std.DeptId;
                    studentToBeUpdated.StdImg = std.StdImg;
                    studentToBeUpdated.Email = std.Email;
                    studentToBeUpdated.Password = std.Password;
                    studentToBeUpdated.UserName = std.UserName;

                    db.Students.Update(studentToBeUpdated);
                    db.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }

            }
            ViewBag.depts = new SelectList(db.Departments.ToList(), "DeptId", "Name", std.DeptId);
            return Json("Modify your data");

        }
        
        public IActionResult Delete(int? id)
        {
            if (id == null) {
                return NotFound();
            }
            Student std = db.Students.FirstOrDefault(a => a.Id == id);

            if (std is null)
            {
                return NotFound();
            }

            return View(std);
        }
        [ActionName("Delete")]
        [HttpPost]
        public IActionResult DeleteConfirmed(int? id)
        {
            if(id == null)
            {
                return NotFound(id);
            }
            Student std = db.Students.FirstOrDefault(x => x.Id == id);
            if (std is null)
            {
                return NotFound();
            }
            db.Students.Remove(std);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

ConnectingToDB_Lab3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConnectingToDB_Lab3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ConnectingToDB_Lab3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ConnectingToDB_Lab3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ConnectingToDB_Lab3/Views/Shared/_Layout2.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
      
              <nav class="navbar nav-bar-light navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3" style="font-size: 15px;" >
                <div class="container-fluid">
                    <a class="navbar-brand m-1" asp-area="" asp-controller="Home" asp-action="Index" style="color: white;">Lab3</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                            </li>
                        
                        </ul>
                    </div>
                </div>
              </nav>      
            @RenderBody()
            <footer class="bg-white text-center text-dark  border-top" style=" width: 90vw; background:white; ">
 
              <!-- Copyright -->
              <div class="text-center p-3" >
                © 2020 Copyright:
                <a  class="text-dark" href="https://mdbootstrap.com/">Footer @@ITI @DateTime.Now.Year</a>
              </div>
              <!-- Copyright -->
            </footer>
            <script src="~/lib/jquery/dist/jquery.js"></script>
            @RenderSection("scripts",false)

</body>
</html>